"""
Django settings for backend_core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env if present
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str]) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name: str, default: int) -> int:
    raw_value = os.getenv(name, str(default)).strip()
    try:
        return int(raw_value)
    except ValueError:
        return default

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-+8p%-euri4fv$38s#hs#+k)i-_8yi=xjudvy5!&f@8+z%5mt_h",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

DEFAULT_ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    "host.docker.internal",
]
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [    
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "accounts",
    "corsheaders",
    "rest_framework",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail.contrib.table_block",
    "modelcluster",
    "taggit",
    "blog",
    "api",
    "ntr",
    "billing",
    "nutrition",
    "insight_ai",
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = 'backend_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend_core.context_processors.public_urls',
            ],
            # Ensure custom template filters are globally available
            'builtins': [
                'ntr.templatetags.compat',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").strip().lower()
SQLITE_PATH = os.getenv("SQLITE_PATH", "").strip()

if DB_ENGINE in {"postgres", "postgresql", "psql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "insightpilot"),
            "USER": os.getenv("POSTGRES_USER", "insightpilot"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "insightpilot_dev_pw"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_PATH or (BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CET'

USE_I18N = True

USE_TZ = True


# Admin timestamp display
DATETIME_FORMAT = "Y-m-d H:i:s \\C\\E\\T"
SHORT_DATETIME_FORMAT = "Y-m-d H:i \\C\\E\\T"
TIME_FORMAT = "H:i:s \\C\\E\\T"
SHORT_TIME_FORMAT = "H:i \\C\\E\\T"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media uploads (used by Wagtail images/documents)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Used by Wagtail for absolute admin URLs in emails / user bar.
WAGTAILADMIN_BASE_URL = os.getenv("WAGTAILADMIN_BASE_URL", "http://localhost:8000").strip()

# Display name shown in the Wagtail admin.
WAGTAIL_SITE_NAME = "InsightPilot"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FRONTEND_BASE_URL = "http://localhost:5173"
LOCAL_FRONTEND_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", DEFAULT_FRONTEND_BASE_URL).strip().rstrip("/")

default_cors_allowed_origins = [*LOCAL_FRONTEND_ORIGINS]
if FRONTEND_BASE_URL and FRONTEND_BASE_URL not in default_cors_allowed_origins:
    default_cors_allowed_origins.append(FRONTEND_BASE_URL)

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default_cors_allowed_origins)
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG)
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default_cors_allowed_origins)

USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# NicheTrendRadar external connectors
# YouTube Data API key (used by youtube_client).
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")

# Nutrition external connectors
USDA_FOODDATA_CENTRAL_API_KEY = os.getenv("USDA_FOODDATA_CENTRAL_API_KEY", "").strip()

# InsightPilot AI (private nutrition AI test)
INSIGHT_AI_PROVIDER = os.getenv("INSIGHT_AI_PROVIDER", "gemini").strip().lower()
INSIGHT_AI_GEMINI_API_KEY = os.getenv("INSIGHT_AI_GEMINI_API_KEY", "").strip()
INSIGHT_AI_MODEL = os.getenv("INSIGHT_AI_MODEL", "gemini-2.5-flash-lite").strip()
INSIGHT_AI_OPENAI_API_KEY = os.getenv("INSIGHT_AI_OPENAI_API_KEY", os.getenv("OPENAI_API_KEY", "")).strip()
INSIGHT_AI_OPENAI_MODEL = os.getenv("INSIGHT_AI_OPENAI_MODEL", "gpt-4.1-nano").strip()
INSIGHT_AI_ALLOWED_EMAILS = os.getenv("INSIGHT_AI_ALLOWED_EMAILS", "").strip()
INSIGHT_AI_MONTHLY_MESSAGE_LIMIT = env_int("INSIGHT_AI_MONTHLY_MESSAGE_LIMIT", 100)
INSIGHT_AI_MONTHLY_TOKEN_LIMIT = env_int("INSIGHT_AI_MONTHLY_TOKEN_LIMIT", 100000)
INSIGHT_AI_MAX_OUTPUT_TOKENS = env_int("INSIGHT_AI_MAX_OUTPUT_TOKENS", 700)
INSIGHT_AI_TIMEOUT_SECONDS = env_int("INSIGHT_AI_TIMEOUT_SECONDS", 30)

# MercadoLibre OAuth configuration (used by mercadolibre_client).
MERCADOLIBRE_CLIENT_ID = os.getenv("MERCADOLIBRE_CLIENT_ID", "")
MERCADOLIBRE_CLIENT_SECRET = os.getenv("MERCADOLIBRE_CLIENT_SECRET", "")
MERCADOLIBRE_REDIRECT_URI = os.getenv("MERCADOLIBRE_REDIRECT_URI", "")
MERCADOLIBRE_ACCESS_TOKEN = os.getenv("MERCADOLIBRE_ACCESS_TOKEN", "")

# Shared secret for internal automation calls (e.g., n8n -> InsightPilot).
INSIGHTPILOT_INTERNAL_TOKEN = os.getenv("INSIGHTPILOT_INTERNAL_TOKEN", "").strip()

# Email (SMTP) configuration for password reset emails.
EMAIL_HOST = os.getenv("EMAIL_HOST", "").strip()
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@insightpilot.local")

if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# OAuth providers
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "").strip()
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI", "").strip()

FACEBOOK_APP_ID = os.getenv("FACEBOOK_APP_ID", "").strip()
FACEBOOK_APP_SECRET = os.getenv("FACEBOOK_APP_SECRET", "").strip()
FACEBOOK_REDIRECT_URI = os.getenv("FACEBOOK_REDIRECT_URI", "").strip()

FRONTEND_OAUTH_REDIRECT_PATH = os.getenv("FRONTEND_OAUTH_REDIRECT_PATH", "/oauth/callback").strip()

# Stripe billing
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "").strip()
STRIPE_GRACE_DAYS = int(os.getenv("STRIPE_GRACE_DAYS", "7"))
