# Generated by Django 5.2.8 on 2026-03-15 14:29

import django.core.validators
import django.db.models.deletion
import nutrition.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('track', 'Track'), ('maintain', 'Maintain'), ('lose', 'Lose'), ('gain', 'Gain')], default='track', max_length=20)),
                ('daily_calorie_target', models.PositiveIntegerField(default=2000)),
                ('protein_target_grams', models.FloatField(default=150.0)),
                ('carbs_target_grams', models.FloatField(default=250.0)),
                ('fat_target_grams', models.FloatField(default=70.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition profile',
                'verbose_name_plural': 'Nutrition profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('serving_description', models.CharField(default='1 serving', max_length=120)),
                ('calories', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('protein_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('carbs_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fat_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fiber_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sugar_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sodium_mg', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
                'indexes': [models.Index(fields=['owner', 'name'], name='nutrition_food_owner_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=nutrition.models.default_entry_date)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('food_source', models.CharField(choices=[('usda', 'USDA'), ('custom', 'Custom'), ('recent', 'Recent'), ('demo', 'Demo')], default='usda', max_length=20)),
                ('external_food_id', models.CharField(blank=True, default='', max_length=120)),
                ('food_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('serving_description', models.CharField(default='1 serving', max_length=120)),
                ('servings', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('serving_calories', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('serving_protein_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('serving_carbs_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('serving_fat_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('serving_fiber_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('serving_sugar_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('serving_sodium_mg', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('calories', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('protein_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('carbs_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fat_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fiber_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sugar_grams', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sodium_mg', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entry_date', 'meal_type', 'created_at'],
                'indexes': [models.Index(fields=['owner', 'entry_date'], name='nutrition_entry_owner_date_idx'), models.Index(fields=['owner', 'meal_type'], name='nutrition_entry_owner_meal_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=nutrition.models.default_entry_date)),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'entry_date'], name='nutr_weight_owner_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'entry_date'), name='nutr_weight_owner_date_uniq')],
            },
        ),
    ]
