# Generated by Django 5.2.8 on 2026-04-17 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfood',
            name='base_amount',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='customfood',
            name='base_unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz'), ('ml', 'mL'), ('cup', 'cup'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('piece', 'piece'), ('serving', 'serving')], default='serving', max_length=20),
        ),
        migrations.AddField(
            model_name='customfood',
            name='external_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customfood',
            name='gram_weight',
            field=models.FloatField(blank=True, help_text='Optional gram weight for the base amount.', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='customfood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nutrition_foods/'),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='grams_per_unit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='measurement_unit',
            field=models.CharField(blank=True, default='serving', max_length=40),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='total_grams',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='serving_description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
