# Generated by Django 5.2.8 on 2026-02-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_customer_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('monthly_price_cents', models.PositiveIntegerField()),
                ('tool_limit', models.PositiveSmallIntegerField()),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price_cents', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_change_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_tool_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='access_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.accesspass'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_access_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='billing.accesspass'),
        ),
    ]
