# Generated by Django 5.2.8 on 2026-02-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_seed_access_passes_and_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], default='draft', max_length=30)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('amount_due_cents', models.IntegerField(default=0)),
                ('amount_paid_cents', models.IntegerField(default=0)),
                ('amount_remaining_cents', models.IntegerField(default=0)),
                ('billing_reason', models.CharField(blank=True, default='', max_length=80)),
                ('hosted_invoice_url', models.URLField(blank=True, default='')),
                ('invoice_pdf_url', models.URLField(blank=True, default='')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=255)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_created_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.subscription')),
            ],
            options={
                'ordering': ['-stripe_created_at', '-created_at'],
            },
        ),
    ]
