# Generated by Django 5.2.8 on 2025-11-25 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the trend track, e.g. 'Standing desks in EU'.", max_length=200)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keywords to monitor for this track.')),
                ('market_region', models.CharField(default='Global', help_text="Market region, e.g. 'EU', 'US', or 'Global'.", max_length=50)),
                ('category', models.CharField(blank=True, help_text='Optional category label for grouping tracks.', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', help_text='Is this track active or paused?', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often to refresh trend data for this track.', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the trend automation last ran for this track.', null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='When the trend automation is next scheduled to run.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this track was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this track was last updated.')),
                ('owner', models.ForeignKey(help_text='User who owns this trend track.', on_delete=django.db.models.deletion.CASCADE, related_name='ntr_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
