# Generated by Django 5.2.8 on 2025-11-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='country',
            field=models.CharField(blank=True, help_text="Optional country code like 'US', 'DE', 'MK' (ISO 3166-1 alpha-2).", max_length=2),
        ),
        migrations.AddField(
            model_name='track',
            name='language',
            field=models.CharField(blank=True, help_text="Optional language code like 'en', 'de', 'mk'.", max_length=5),
        ),
        migrations.AddField(
            model_name='track',
            name='platform',
            field=models.CharField(choices=[('google', 'Google'), ('reddit', 'Reddit'), ('tiktok', 'TikTok')], default='google', help_text='Which platform this track should monitor (Google, Reddit, TikTok...).', max_length=20),
        ),
    ]
