# Generated by Django 5.2.8 on 2025-12-02 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntr', '0002_track_country_track_language_track_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('shopify', 'Shopify'), ('etsy', 'Etsy')], default='amazon', help_text='Which platform this track should monitor (Amazon, Shopify, Etsy...).', max_length=20),
        ),
        migrations.CreateModel(
            name='NtrSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(blank=True, default=list, help_text="List of selling platforms, e.g. ['amazon', 'shopify'].")),
                ('sources', models.JSONField(blank=True, default=list, help_text="List of data sources, e.g. ['google_trends', 'tiktok'].")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When these settings were created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these settings were last updated.')),
                ('owner', models.OneToOneField(help_text='User that owns these NTR settings.', on_delete=django.db.models.deletion.CASCADE, related_name='ntr_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
