# Generated by Django 5.2.8 on 2025-12-03 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntr', '0003_alter_track_platform_ntrsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ntrsettings',
            options={'verbose_name': 'NTR setting', 'verbose_name_plural': 'NTR settings'},
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(help_text='Timestamp when this snapshot was generated.')),
                ('platform', models.CharField(help_text="Platform for this snapshot, e.g. 'Amazon', 'Shopify', or 'Etsy'.", max_length=50)),
                ('source', models.CharField(blank=True, help_text="Optional: data source for this snapshot, e.g. 'google_trends', 'reddit'.", max_length=50)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Flexible structure to store trend metrics, e.g. {"search_volume": 1234, "mention_count": 456, "trend_direction": "up" }.')),
                ('summary', models.TextField(blank=True, help_text='Short human readable summary of this snapshot.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this snapshot row was created in the database.')),
                ('track', models.ForeignKey(help_text='Trend track this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ntr.track')),
            ],
        ),
    ]
