# Generated by Django 5.2.8 on 2025-12-18 19:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('table', 5), ('code', 6), ('call_to_action', 9), ('toc_marker', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed a URL (YouTube, Vimeo, etc.)'}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Code snippet (renders in a pre/code block).', 'rows': 8, 'template': 'blog/blocks/code_block.html'}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('label', 7), ('url', 8)]], {'icon': 'plus', 'template': 'blog/blocks/cta.html'}), 10: ('wagtail.blocks.StructBlock', [[]], {})}),
        ),
    ]
