# Generated by Django 5.2.8 on 2025-12-18 19:56

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpostpage_body'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(blank=True, help_text='Optional HEX color for badges (e.g. #0d9488).', max_length=16)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or icon class used in templates.', max_length=64)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='CallToActionSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True)),
                ('button_label', models.CharField(max_length=64)),
                ('button_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Call to action',
                'verbose_name_plural': 'Call to actions',
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='author_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Optional focus keyword for SEO.', max_length=120),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Used for social sharing cards; falls back to hero if empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('table_of_contents', 11), ('rich_text', 12), ('heading', 15), ('paragraph', 12), ('quote', 18), ('callout', 21), ('code', 24), ('table', 25), ('image', 28), ('image_gallery', 29), ('video', 30), ('embed', 30), ('raw_html', 31), ('two_column', 34), ('feature_grid', 38), ('call_to_action', 40), ('cta', 42), ('cta_snippet', 44), ('divider', 45), ('faq', 48), ('accordion', 51), ('toc_marker', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small label above the title.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('subtitle', 2), ('background_image', 3), ('button_text', 4), ('button_url', 5)]], {}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Auto-generate from H2/H3 in the article body.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Matches the heading anchor ID'}), 9: ('wagtail.blocks.StructBlock', [[('label', 1), ('anchor_id', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Optional manual overrides. Leave empty to auto-build.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('auto', 7), ('manual_items', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr']}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Choose the heading level.'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Heading text.', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('level', 13), ('text', 14)]], {}), 16: ('wagtail.blocks.TextBlock', (), {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it?', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('quote', 16), ('attribution', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning')]}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 21: ('wagtail.blocks.StructBlock', [[('kind', 19), ('title', 4), ('body', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Language hint, e.g. python, js, bash. Used as a CSS class.', 'required': False}), 23: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste code; rendered inside <pre><code>.', 'rows': 10}), 24: ('wagtail.blocks.StructBlock', [[('language', 22), ('code', 23)]], {}), 25: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full width')]}), 28: ('wagtail.blocks.StructBlock', [[('image', 26), ('caption', 4), ('alignment', 27)]], {}), 29: ('blog.blocks.ImageGalleryBlock', (), {}), 30: ('blog.blocks.VideoEmbedBlock', (), {}), 31: ('blog.blocks.RawHTMLBlock', (), {}), 32: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 33: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Place the image on the left and text on the right.', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('left_content', 32), ('right_image', 3), ('swap', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji or icon class.', 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('icon', 35), ('title', 1), ('text', 16)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'help_text': 'Add 3–6 concise features.'}), 38: ('wagtail.blocks.StructBlock', [[('items', 37)]], {}), 39: ('wagtail.blocks.URLBlock', (), {}), 40: ('wagtail.blocks.StructBlock', [[('label', 1), ('url', 39)]], {}), 41: ('wagtail.blocks.TextBlock', (), {'required': False}), 42: ('wagtail.blocks.StructBlock', [[('headline', 1), ('text', 41), ('button_label', 1), ('button_url', 39)]], {}), 43: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.CallToActionSnippet',), {}), 44: ('wagtail.blocks.StructBlock', [[('snippet', 43)]], {}), 45: ('blog.blocks.DividerBlock', (), {}), 46: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 20)]], {}), 47: ('wagtail.blocks.ListBlock', (46,), {}), 48: ('wagtail.blocks.StructBlock', [[('items', 47)]], {}), 49: ('wagtail.blocks.StructBlock', [[('title', 1), ('content', 20)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {}), 51: ('wagtail.blocks.StructBlock', [[('items', 50)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogcategory'),
        ),
        migrations.CreateModel(
            name='BlogPostPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpostpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
